services:
  - type: web
    name: funnelbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app --timeout 600 --workers 1 --threads 2 --preload
    envVars:
      - key: GEMINI_API_KEY
        sync: false
    plan: starter # Using the paid plan to get more memory